# Site settings
title: remarkablemark
email: mark@remarkablemark.org
description: > # this means to ignore newlines until "baseurl:"
    Mark's remarkable site.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://remarkablemark.org" # the base hostname & protocol for your site
github_username: remarkablemark
repository: https://github.com/remarkablemark/remarkablemark.github.io
google_analytics_id: UA-59233605-1

# Build settings
markdown: kramdown
highlighter: rouge
sass:
    style: :compressed
permalink: /blog/:year/:month/:day/:title/
encoding: utf-8
