# Site settings
title: remarkablemark
email: mark@remarkablemark.org
description: Site of remarkablemark.
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://remarkablemark.org # the base hostname & protocol for your site
github_username: remarkablemark
repository: remarkablemark/remarkablemark.github.io
google_analytics_id: UA-59233605-1
disqus_shortname: remarkablemark
assets_path: //remarkablemark.org/assets

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  style: :compressed
permalink: /blog/:year/:month/:day/:title/
timezone: America/New_York
encoding: utf-8
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .travis.yml
  - vendor
  - README.md
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
