# Site settings
#
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: remarkablemark
email: mark@remarkablemark.org
description: >- # this means to ignore newlines until "baseurl:"
  remarkablemark's site.
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://remarkablemark.org # the base hostname & protocol for your site, e.g. http://example.com
github_username: remarkablemark
repository: remarkablemark/remarkablemark.github.io
google_analytics_id: UA-59233605-1
disqus_shortname: remarkablemark
assets_path: /assets

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  style: :compressed
permalink: /blog/:year/:month/:day/:title/
timezone: America/New_York
encoding: utf-8
safe: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
#
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # Custom
  - CNAME
  - README.md
